//! Definitions for IKEv2 implementation

pub mod constants;
pub mod header;
mod impls;
pub mod params;

use params::CertificateEncoding;
use params::EncryptionAlgorithm;
use params::ExchangeType;
use params::IntegrityAlgorithm;
use params::KeyExchangeMethod;
use params::NotifyErrorMessage;
use params::NotifyStatusMessage;
use params::PseudorandomFunction;
use params::SecurityProtocol;
use params::SequenceNumberType;
use serde::Deserialize;
use serde::Serialize;
use strum::Display;

pub use super::super::v1::definitions::GenericPayloadHeader;
pub use super::super::v1::definitions::Header;

/// When parsing a parameter from u8, there are several "regions" in the definitions
/// that can't be defined by Rusts enum. Typically, the last two regions of the
/// parameter definitions are unassigned and/or reserved for private use.
#[derive(Debug, Clone, Display, Copy, Serialize, Deserialize)] //
#[derive(Hash, Ord, PartialOrd, Eq, PartialEq)]
#[repr(u8)]
pub enum UnparseableParameter {
    /// The parameter is reserved and must not be used, as it may conflict with older standards
    Reserved,
    /// The parameter has no recognized meaning by any known standard
    Unassigned,
    /// The parameter is reserved for Private Use by proprietary implementations
    /// and not part of a standard
    PrivateUse,
    /// The parameter can not reach the value this resolves to,
    /// as such the packet where it originates from must be invalid
    OutOfRange,
    /// The parameter is not allowed in the current context, because an encryption
    /// algorithm that is only valid in the context of ESP but used in IKE
    NotAllowed(EncryptionAlgorithm),
}

/// High-level representation of an IKEv2 message (ISAKMP packet)
#[derive(Debug, PartialEq)]
pub struct IKEv2 {
    /// Cookie of the entity initiating the establishment of the Security Association.
    /// The value is chosen by the initiator, and it MUST NOT be zero.
    pub initiator_cookie: u64,
    /// Cookie of entity that is responding to a previous request of some sort.
    /// The value is chosen by the responder to identify a unique IKE Security Association.
    /// This value MUST be zero in the first message of an IKE initial exchange
    /// (including repeats of that message including a cookie).
    pub responder_cookie: u64,
    /// Type of packet defining the general state of the ongoing IKE "conversation",
    /// see [ExchangeType] for possible options. This constrains the payloads sent
    /// in each message in an exchange.
    pub exchange_type: ExchangeType,
    /// Flag indicating whether the packet is sent by the initiator, as
    /// this bit MUST be set in messages sent by the
    /// original initiator of the IKE SA and MUST be cleared in
    /// messages sent by the original responder. It is used by the
    /// recipient to determine which eight octets of the SPI were
    /// generated by the recipient. This bit changes to reflect who
    /// initiated the last rekey of the IKE SA.
    pub initiator: bool,
    /// This bit indicates that this message is a
    /// response to a message containing the same Message ID. This bit
    /// MUST be cleared in all request messages and MUST be set in all
    /// responses. An IKE endpoint MUST NOT generate a response to a
    /// message that is marked as being a response.
    pub response: bool,
    /// Message identifier used to control retransmission of lost packets and matching
    /// of requests and responses. It is essential to the security of the protocol
    /// because it is used to prevent message replay attacks.
    pub message_id: u32,
    /// Ordered list of payloads found in the IKEv2 packet
    pub payloads: Vec<Payload>,
}

/// Generic payload of an IKE message including its types
///
/// See [PayloadType] for the type definitions, all types listed there
/// but not implemented here are simply not supported
#[derive(Debug, PartialEq)]
pub enum Payload {
    /// Container for [SecurityAssociation]s
    SecurityAssociation(SecurityAssociation),
    KeyExchange(KeyExchange),
    CertificateRequest(CertificateRequest),

    /// Container for random data used to guarantee liveness during an
    /// exchange and protect against replay attacks. The size of the Nonce Data
    /// MUST be between 16 and 256 octets, inclusive. Nonce values MUST NOT be reused.
    Nonce(Vec<u8>),
    Notify(Notification),
    Delete(Deletion),

    /// Vendor-defined constant value that allow clients to discover peers
    /// with vendor-specific functionality in the private-use areas of various
    /// types in the document and enable vendor-specific extensions.
    ///
    /// Multiple VendorID payloads may be present in a single IKEv2 message.
    /// It is the responsibility of the person choosing the Vendor ID to assure
    /// its uniqueness in spite of the absence of any central registry for IDs.
    VendorID(Vec<u8>),
    EncryptedAndAuthenticated(Vec<u8>),
}

/// High-level representation of a Security Association
///
/// See its [SecurityAssociation::try_build] and [SecurityAssociation::try_parse]
/// methods and associated functions, respectively.
///
/// A Security Association MAY contain multiple proposals. If there is
/// more than one, they MUST be ordered from most preferred to least
/// preferred. Each proposal contains a single IPsec protocol (where a
/// protocol is IKE, ESP, or AH), each protocol MAY contain multiple
/// transforms, and each transform MAY contain multiple attributes.
///
/// One reason to use multiple proposals is to propose both standard crypto
/// ciphers and combined-mode ciphers. Combined-mode ciphers include
/// both integrity and encryption in a single encryption algorithm, and
/// MUST either offer no integrity algorithm or a single integrity
/// algorithm of "NONE", with no integrity algorithm being the
/// RECOMMENDED method. If an initiator wants to propose both combined-mode
/// ciphers and normal ciphers, it must include two proposals: one
/// will have all the combined-mode ciphers, and the other will have all
/// the normal ciphers with the integrity algorithms.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct SecurityAssociation {
    pub proposals: Vec<Proposal>,
}

// #[derive(Debug, Clone, Display, EnumIter, Copy, Serialize, Deserialize)] //
// #[derive(Hash, Ord, PartialOrd, Eq, PartialEq)]

/// High-level representation of a Proposal
///
/// Each Proposal/Protocol structure is followed by one or more transform
/// structures. The number of different transforms is generally
/// determined by the Protocol. IKE generally has four transforms: a
/// Diffie-Hellman group, an integrity check algorithm, a PRF algorithm,
/// and an encryption algorithm. For each Protocol, the set of
/// permissible transforms is assigned Transform ID numbers, which appear
/// in the header of each transform.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Proposal {
    /// Identifier for the security protocol to be used in this proposal,
    /// must be [SecurityProtocol::InternetKeyExchange] to work in this project
    pub protocol: SecurityProtocol,
    /// Optional sending entity's SPI (Security Parameter Index), currently not used
    /// for scanning and not needed to be duplicated from the [SecurityAssociation]
    pub spi: Vec<u8>,

    /// List of encryption algorithms and optional key length that should be proposed;
    /// mixing AEAD and non-AEAD encryption algorithms in a single proposal is illegal
    pub encryption_algorithms: Vec<(EncryptionAlgorithm, Option<u16>)>,
    /// List of PRF (pseudo-random function) algorithms that should be proposed
    pub pseudo_random_functions: Vec<PseudorandomFunction>,
    /// List of integrity algorithms (aka MAC) that should be proposed;
    /// note that integrity algorithms are optional if the encryption algorithms are
    /// AEADs, and mandatory otherwise
    pub integrity_algorithms: Vec<IntegrityAlgorithm>,
    /// Key exchange methods (aka DH groups) that should be proposed
    pub key_exchange_methods: Vec<KeyExchangeMethod>,
    /// Sequence numbers used in this proposal, only valid for non-IKE protocols
    pub sequence_numbers: Vec<SequenceNumberType>,
}

/// High-level representation of a transformation and all required additional
/// information that is dynamically built from incoming packets. See [TransformType].
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(missing_docs)]
pub enum Transform {
    Encryption(EncryptionAlgorithm, Option<u16>),
    PseudoRandomFunction(PseudorandomFunction),
    Integrity(IntegrityAlgorithm),
    KeyExchange(KeyExchangeMethod),
    SequenceNumber(SequenceNumberType),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum Attribute {
    /// Key-length in bits for variable-length encryption ciphers like AES-CBC
    KeyLength(u16),
}

/// High-level representation of a Key Exchange
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KeyExchange {
    /// Indicator which key exchange method is used in the following `data` field
    pub dh_group: KeyExchangeMethod,
    /// Raw data of the key exchange, where the structure is defined by the DH group
    pub data: Vec<u8>,
}

/// High-level representation of a Certificate Request
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CertificateRequest {
    pub encoding: CertificateEncoding,
    pub certification_authority: Vec<u8>,
}

/// High-level representation of notifications between peers
///
/// Error and status messages may have additional data, depending on their type.
/// For this representation, these are not parsed and provided as [`Vec<u8>`] instead.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Notification {
    pub variant: NotificationType,
    pub data: Vec<u8>,
    pub protocol: SecurityProtocol,
    pub spi: Option<Vec<u8>>,
}

/// Variant of a notification defining the structure of the arbitrary
/// data in the `data` field of the [Notification]
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(missing_docs)]
pub enum NotificationType {
    Error(NotifyErrorMessage),
    Status(NotifyStatusMessage),
}

/// High-level representation of a Deletion (Delete payload)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Deletion {
    /// Delete the IKE SA itself
    InternetKeyExchange,
    /// Delete a list of AH SPIs
    AuthenticationHeader(Vec<u32>),
    /// Delete a list of ESP SPIs
    EncapsulatingSecurityPayload(Vec<u32>),
}
